export type Provider = "openai" | "google" | "anthropic" | "opencode";

export type ScoreKey =
  | "summary"
  | "roleFidelity"
  | "quality"
  | "personaStability"
  | "robustness"
  | "recovery";

export type ModelResult = {
  id: string;
  name: string;
  provider: Provider;
  providerLabel: string;
  rank: number | null;
  reference?: boolean;
  summary: number;
  majorFree: number;
  scenarios: number;
  major: number;
  legacyAverage: number;
  metrics: Record<Exclude<ScoreKey, "summary">, number>;
  tracks: {
    adversarial: number;
    coreJa: number;
    custom: number;
    legacyBase: number;
    multiTurn: number;
  };
  legacyDimensions: Record<string, number>;
};

export const benchmarkMeta = {
  title: "Japanese-RP-Bench v2",
  updatedAt: "2026-07-25",
  modelCount: 13,
  referenceModelCount: 1,
  scenariosPerModel: 36,
  judgeCount: 3,
  incompleteNote:
    "Claude Fable 5は1件を同一条件で5回拒否後に除外。35/36の参考値として表示し、正式順位は「-」",
};

export const metricMeta: Record<
  ScoreKey,
  { label: string; short: string; description: string }
> = {
  summary: {
    label: "RP Summary",
    short: "RP要約",
    description:
      "Role Fidelity・Quality・Persona Stability・Robustness・Recoveryの単純平均。Qualityを通じて旧8指標を間接的に含む",
  },
  roleFidelity: {
    label: "Role Fidelity",
    short: "役柄追従",
    description: "人格、設定、関係性、知識境界、口調などのルールへの追従性",
  },
  quality: {
    label: "Conversation Quality",
    short: "会話品質",
    description: "自然さ、表現力、創造性、会話の楽しさ",
  },
  personaStability: {
    label: "Persona Stability",
    short: "人格安定",
    description: "会話の進行に伴って人格・設定への追従度が低下しなかったか",
  },
  robustness: {
    label: "Robustness",
    short: "耐性",
    description: "人格置換、引用内命令、偽記憶などへの耐性",
  },
  recovery: {
    label: "Recovery",
    short: "復帰",
    description: "攻撃や誤誘導のあと、元の人格へ戻れるか",
  },
};

export const results: ModelResult[] = [
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 mini",
    provider: "openai",
    providerLabel: "OpenAI",
    rank: 1,
    summary: 96.66,
    majorFree: 35,
    scenarios: 36,
    major: 1,
    legacyAverage: 4.425,
    metrics: {
      roleFidelity: 99.054,
      quality: 86.328,
      personaStability: 97.917,
      robustness: 100,
      recovery: 100,
    },
    tracks: {
      adversarial: 98.809,
      coreJa: 100,
      custom: 100,
      legacyBase: 99,
      multiTurn: 98.333,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.633,
      Consistency: 4.711,
      "Contextual Understanding": 4.644,
      Expressiveness: 4.1,
      Creativity: 4.011,
      "Naturalness of Japanese": 4.644,
      "Enjoyment of the Dialogue": 4.167,
      "Appropriateness of Turn-Taking": 4.489,
    },
  },
  {
    id: "gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    provider: "openai",
    providerLabel: "OpenAI",
    rank: 2,
    summary: 95.97,
    majorFree: 35,
    scenarios: 36,
    major: 1,
    legacyAverage: 4.455,
    metrics: {
      roleFidelity: 95.718,
      quality: 86.91,
      personaStability: 97.222,
      robustness: 100,
      recovery: 100,
    },
    tracks: {
      adversarial: 100,
      coreJa: 100,
      custom: 100,
      legacyBase: 94.889,
      multiTurn: 99.167,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.4,
      Consistency: 4.633,
      "Contextual Understanding": 4.689,
      Expressiveness: 4.255,
      Creativity: 4.255,
      "Naturalness of Japanese": 4.711,
      "Enjoyment of the Dialogue": 4.333,
      "Appropriateness of Turn-Taking": 4.367,
    },
  },
  {
    id: "gemini-3.6-flash",
    name: "Gemini 3.6 Flash",
    provider: "google",
    providerLabel: "Google",
    rank: 3,
    summary: 95.101,
    majorFree: 35,
    scenarios: 36,
    major: 1,
    legacyAverage: 4.381,
    metrics: {
      roleFidelity: 95.833,
      quality: 85.46,
      personaStability: 94.213,
      robustness: 100,
      recovery: 100,
    },
    tracks: {
      adversarial: 100,
      coreJa: 100,
      custom: 100,
      legacyBase: 95,
      multiTurn: 100,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.3,
      Consistency: 4.589,
      "Contextual Understanding": 4.556,
      Expressiveness: 4.278,
      Creativity: 4.089,
      "Naturalness of Japanese": 4.533,
      "Enjoyment of the Dialogue": 4.3,
      "Appropriateness of Turn-Taking": 4.4,
    },
  },
  {
    id: "qwen3.7-max",
    name: "Qwen3.7 Max",
    provider: "opencode",
    providerLabel: "OpenCode Go",
    rank: 4,
    summary: 93.691,
    majorFree: 35,
    scenarios: 36,
    major: 2,
    legacyAverage: 4.403,
    metrics: {
      roleFidelity: 95.532,
      quality: 85.699,
      personaStability: 97.639,
      robustness: 93.75,
      recovery: 95.833,
    },
    tracks: {
      adversarial: 98.334,
      coreJa: 93.75,
      custom: 100,
      legacyBase: 95.333,
      multiTurn: 95,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.422,
      Consistency: 4.678,
      "Contextual Understanding": 4.622,
      Expressiveness: 4.222,
      Creativity: 4.144,
      "Naturalness of Japanese": 4.511,
      "Enjoyment of the Dialogue": 4.211,
      "Appropriateness of Turn-Taking": 4.411,
    },
  },
  {
    id: "claude-opus-5",
    name: "Claude Opus 5",
    provider: "anthropic",
    providerLabel: "Anthropic",
    rank: 5,
    summary: 95.559,
    majorFree: 34,
    scenarios: 36,
    major: 2,
    legacyAverage: 4.507,
    metrics: {
      roleFidelity: 95.278,
      quality: 88.537,
      personaStability: 93.981,
      robustness: 100,
      recovery: 100,
    },
    tracks: {
      adversarial: 100,
      coreJa: 100,
      custom: 100,
      legacyBase: 94.333,
      multiTurn: 100,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.4,
      Consistency: 4.7,
      "Contextual Understanding": 4.722,
      Expressiveness: 4.378,
      Creativity: 4.4,
      "Naturalness of Japanese": 4.656,
      "Enjoyment of the Dialogue": 4.389,
      "Appropriateness of Turn-Taking": 4.411,
    },
  },
  {
    id: "kimi-k3",
    name: "Kimi K3",
    provider: "opencode",
    providerLabel: "OpenCode Go",
    rank: 6,
    summary: 90.861,
    majorFree: 34,
    scenarios: 36,
    major: 3,
    legacyAverage: 4.107,
    metrics: {
      roleFidelity: 93.383,
      quality: 79.786,
      personaStability: 87.384,
      robustness: 93.75,
      recovery: 100,
    },
    tracks: {
      adversarial: 100,
      coreJa: 95.833,
      custom: 97.619,
      legacyBase: 92.444,
      multiTurn: 99.167,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.389,
      Consistency: 4.444,
      "Contextual Understanding": 4.4,
      Expressiveness: 3.789,
      Creativity: 3.533,
      "Naturalness of Japanese": 4.344,
      "Enjoyment of the Dialogue": 3.811,
      "Appropriateness of Turn-Taking": 4.144,
    },
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    provider: "google",
    providerLabel: "Google",
    rank: 7,
    summary: 89.49,
    majorFree: 32,
    scenarios: 36,
    major: 10,
    legacyAverage: 4.374,
    metrics: {
      roleFidelity: 94.12,
      quality: 85.045,
      personaStability: 93.287,
      robustness: 75,
      recovery: 100,
    },
    tracks: {
      adversarial: 100,
      coreJa: 100,
      custom: 100,
      legacyBase: 93.444,
      multiTurn: 85,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.211,
      Consistency: 4.633,
      "Contextual Understanding": 4.567,
      Expressiveness: 4.289,
      Creativity: 4.133,
      "Naturalness of Japanese": 4.545,
      "Enjoyment of the Dialogue": 4.289,
      "Appropriateness of Turn-Taking": 4.322,
    },
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "opencode",
    providerLabel: "OpenCode Go",
    rank: 8,
    summary: 94.216,
    majorFree: 31,
    scenarios: 36,
    major: 5,
    legacyAverage: 4.347,
    metrics: {
      roleFidelity: 93.38,
      quality: 84.877,
      personaStability: 92.824,
      robustness: 100,
      recovery: 100,
    },
    tracks: {
      adversarial: 100,
      coreJa: 100,
      custom: 100,
      legacyBase: 92.111,
      multiTurn: 98.333,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.1,
      Consistency: 4.6,
      "Contextual Understanding": 4.6,
      Expressiveness: 4.222,
      Creativity: 4.167,
      "Naturalness of Japanese": 4.556,
      "Enjoyment of the Dialogue": 4.255,
      "Appropriateness of Turn-Taking": 4.278,
    },
  },
  {
    id: "minimax-m3",
    name: "MiniMax M3",
    provider: "opencode",
    providerLabel: "OpenCode Go",
    rank: 9,
    summary: 93.206,
    majorFree: 31,
    scenarios: 36,
    major: 5,
    legacyAverage: 4.109,
    metrics: {
      roleFidelity: 91.782,
      quality: 79.458,
      personaStability: 94.792,
      robustness: 100,
      recovery: 100,
    },
    tracks: {
      adversarial: 100,
      coreJa: 97.916,
      custom: 100,
      legacyBase: 90.444,
      multiTurn: 95,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.045,
      Consistency: 4.356,
      "Contextual Understanding": 4.378,
      Expressiveness: 3.922,
      Creativity: 3.689,
      "Naturalness of Japanese": 4.233,
      "Enjoyment of the Dialogue": 3.978,
      "Appropriateness of Turn-Taking": 4.267,
    },
  },
  {
    id: "glm-5.2",
    name: "GLM-5.2",
    provider: "opencode",
    providerLabel: "OpenCode Go",
    rank: 10,
    summary: 90.637,
    majorFree: 31,
    scenarios: 36,
    major: 5,
    legacyAverage: 3.879,
    metrics: {
      roleFidelity: 81.782,
      quality: 74.877,
      personaStability: 96.528,
      robustness: 100,
      recovery: 100,
    },
    tracks: {
      adversarial: 100,
      coreJa: 97.916,
      custom: 100,
      legacyBase: 78.333,
      multiTurn: 98.333,
    },
    legacyDimensions: {
      "Roleplay Adherence": 3.811,
      Consistency: 4.089,
      "Contextual Understanding": 4.378,
      Expressiveness: 3.933,
      Creativity: 4,
      "Naturalness of Japanese": 2.789,
      "Enjoyment of the Dialogue": 3.822,
      "Appropriateness of Turn-Taking": 4.211,
    },
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    provider: "anthropic",
    providerLabel: "Anthropic",
    rank: 11,
    summary: 92.984,
    majorFree: 29,
    scenarios: 36,
    major: 7,
    legacyAverage: 4.29,
    metrics: {
      roleFidelity: 92.593,
      quality: 83.669,
      personaStability: 88.657,
      robustness: 100,
      recovery: 100,
    },
    tracks: {
      adversarial: 100,
      coreJa: 100,
      custom: 100,
      legacyBase: 91.111,
      multiTurn: 100,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.078,
      Consistency: 4.578,
      "Contextual Understanding": 4.578,
      Expressiveness: 4.178,
      Creativity: 3.978,
      "Naturalness of Japanese": 4.533,
      "Enjoyment of the Dialogue": 4.144,
      "Appropriateness of Turn-Taking": 4.255,
    },
  },
  {
    id: "mimo-v2.5-pro",
    name: "MiMo V2.5 Pro",
    provider: "opencode",
    providerLabel: "OpenCode Go",
    rank: 12,
    summary: 87.561,
    majorFree: 29,
    scenarios: 36,
    major: 7,
    legacyAverage: 4.096,
    metrics: {
      roleFidelity: 85.516,
      quality: 79.039,
      personaStability: 93.042,
      robustness: 84.375,
      recovery: 95.833,
    },
    tracks: {
      adversarial: 97.143,
      coreJa: 95.834,
      custom: 97.619,
      legacyBase: 83.333,
      multiTurn: 95,
    },
    legacyDimensions: {
      "Roleplay Adherence": 3.767,
      Consistency: 4.433,
      "Contextual Understanding": 4.489,
      Expressiveness: 4.122,
      Creativity: 4.1,
      "Naturalness of Japanese": 3.578,
      "Enjoyment of the Dialogue": 4.1,
      "Appropriateness of Turn-Taking": 4.178,
    },
  },
  {
    id: "claude-haiku-4.5",
    name: "Claude Haiku 4.5",
    provider: "anthropic",
    providerLabel: "Anthropic",
    rank: 13,
    summary: 90.906,
    majorFree: 25,
    scenarios: 36,
    major: 16,
    legacyAverage: 4.058,
    metrics: {
      roleFidelity: 87.272,
      quality: 78.464,
      personaStability: 90.88,
      robustness: 97.916,
      recovery: 100,
    },
    tracks: {
      adversarial: 98.809,
      coreJa: 97.916,
      custom: 100,
      legacyBase: 85,
      multiTurn: 98.333,
    },
    legacyDimensions: {
      "Roleplay Adherence": 3.467,
      Consistency: 4.344,
      "Contextual Understanding": 4.4,
      Expressiveness: 4.056,
      Creativity: 3.767,
      "Naturalness of Japanese": 4.378,
      "Enjoyment of the Dialogue": 3.9,
      "Appropriateness of Turn-Taking": 4.155,
    },
  },
  {
    id: "claude-fable-5",
    name: "Claude Fable 5",
    provider: "anthropic",
    providerLabel: "Anthropic",
    rank: null,
    reference: true,
    summary: 95.645,
    majorFree: 31,
    scenarios: 35,
    major: 4,
    legacyAverage: 4.493,
    metrics: {
      roleFidelity: 93.714,
      quality: 88.082,
      personaStability: 96.429,
      robustness: 100,
      recovery: 100,
    },
    tracks: {
      adversarial: 100,
      coreJa: 100,
      custom: 100,
      legacyBase: 92.414,
      multiTurn: 100,
    },
    legacyDimensions: {
      "Roleplay Adherence": 4.31,
      Consistency: 4.701,
      "Contextual Understanding": 4.701,
      Expressiveness: 4.425,
      Creativity: 4.379,
      "Naturalness of Japanese": 4.621,
      "Enjoyment of the Dialogue": 4.437,
      "Appropriateness of Turn-Taking": 4.368,
    },
  },
];

export const getScore = (result: ModelResult, key: ScoreKey) =>
  key === "summary" ? result.summary : result.metrics[key];
